import { supabase } from './supabase';
import { TimeRecord } from '../types/timer';

export const saveTimeRecord = async (record: TimeRecord) => {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  const { data: insertData, error: insertError } = await supabase
    .from('time_records')
    .insert({
      // id is auto-generated by database (UUID)
      user_id: user.id,
      start_time: record.startTime.toISOString(),
      stop_time: record.stopTime?.toISOString() || null,
      elapsed_ms: record.elapsedMs,
      status: record.status,
    })
    .select()
    .single();

  if (insertError) {
    console.error('Error saving time record:', insertError);
    throw insertError;
  }

  return insertData;
};

export const fetchTimeRecords = async (): Promise<TimeRecord[]> => {
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    throw new Error('User not authenticated');
  }

  const { data: records, error } = await supabase
    .from('time_records')
    .select('*')
    .eq('user_id', user.id)
    .order('start_time', { ascending: false });

  if (error) {
    console.error('Error fetching time records:', error);
    throw error;
  }

  return records.map((record) => ({
    id: record.id,
    startTime: new Date(record.start_time),
    stopTime: record.stop_time ? new Date(record.stop_time) : undefined,
    elapsedMs: record.elapsed_ms,
    status: record.status as 'idle' | 'running' | 'paused',
  }));
};

export const deleteTimeRecord = async (id: string) => {
  const { error } = await supabase
    .from('time_records')
    .delete()
    .eq('id', id);

  if (error) {
    console.error('Error deleting time record:', error);
    throw error;
  }
};
